name: UnleashedChatManager
main: com.hackhalo2.chat.UnleashedChatManager
version: "${project.version}"
softdepends: [Factions]
author: HACKhalo2
commands:
  me:
    description: "the emote command"
    usage: "/me <String...>"
    permission: ucm.command.me
permissions:
  ucm.*:
    description: Allow the use of all UnleashedChatManager features
    default: op
    children:
      ucm.command.me: true
      ucm.spy: true
  ucm.spy:
    descriptiom: Allow the player to see all chat
    default: op
  ucm.command.*:
    description: Allow the use of all UnleashedChatManager commands
    children:
      ucm.command.me: true
