name: bChatManager
main: net.rymate.bChatManager.bChatManager
depend: [ bPermissions ]
version: 1.1
author: rymate1234
website: www.bukkit.org
description: Chat management plugin for bPermissions based of PEX ChatManager
commands:
  me:
    description: Sends a message such as * rymate1234 said hai!
    usage: /me <message>
    aliases: [m]